@baseUrl = http://localhost:8000/api/v1
@auth = /auth

#signup

#POST {{baseUrl}}{{auth}}/signup
# Accept: application/json
# Content-Type: application/json

# {

# }


#login


POST {{baseUrl}}{{auth}}/login
Accept: application/json
Content-Type: application/json

{
    "email":"dev.frinno@gmail.com",
    "password":"@150505"
}

